import huangsLogo from "../../assets/hjj-logo-black.png";
import { getProfileDisplay } from "../../data/profileDisplay";

export default function ChartFoundationSection({
  report,
  clientName,
  natalPillars,
  tenGodByPillar,
  annualPillar,
  annualZodiac,
  dayMasterLabel,
  dayMasterTrait,
  strongerElements,
  moderateElements,
  weakerElements,
  usefulGod,
  elementalBalance,
  rankedProfiles,
  coverYearLabel,
  onExportJson,
  onExportPdf,
}) {
  return (
    <>
      {/* Print-only cover page */}
      <div className="print-cover hidden print:flex print:flex-col print:items-center print:justify-center print:py-24 print:text-center">
        <img src={huangsLogo} alt="Huangs Jadeite and Jewelry" className="h-16 w-auto mb-6" />
        <p className="text-sm font-bold tracking-widest uppercase mb-4" style={{color:"#8B1A1A"}}>HUANGS JADEITE &amp; JEWELRY</p>
        <h1 className="text-2xl font-bold mb-6 leading-snug" style={{color:"#8B1A1A"}}>
          Personal Feng Shui Energy Analysis<br/>for {coverYearLabel}
        </h1>
        <div className="print-cover-body max-w-md text-sm text-gray-600 leading-relaxed text-left mt-4">
          <p>This personalized Bazi report is designed to help you better understand your elemental balance, natural strengths, emotional tendencies and life direction.</p>
          <p className="mt-3">The purpose of this analysis is to provide guidance and self-awareness in areas such as career, wealth, relationships and health.</p>
        </div>
      </div>

      {/* Print footer — shows on every page via CSS */}
      <div className="print-footer hidden">
        Bazi Analysis generated by huangsjadeiteandjewelry.com.
      </div>

      <div className="mt-7 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-5 print-no-export">
        <p className="text-sm font-bold text-slate-700">Client Profile</p>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={onExportJson}
            className="rounded-xl bg-slate-700 px-5 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-slate-600"
          >
            Export JSON
          </button>
          <button
            type="button"
            onClick={onExportPdf}
            className="rounded-xl bg-amber-700 px-5 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-amber-600"
          >
            Export Client PDF
          </button>
        </div>
      </div>

      {/* Client Profile heading for print */}
      <h2 className="hidden print:block mt-4 text-3xl font-bold" style={{color:"#8B1A1A"}}>Client Profile</h2>
      <div className="hidden print:block border-b mt-1 mb-4" style={{borderColor:"#8B1A1A"}} />

      <table className="mt-4 w-full overflow-hidden rounded-2xl border border-slate-200 text-sm print:rounded-none print:border-[#8B1A1A]">
        <tbody>
          {[
            ["Name", clientName || "-"],
            ["Gender", report.client?.gender || "-"],
            ["Birth Country", report.client?.birthCountry || "-"],
            [
              "Day Master (Horoscope)",
              dayMasterTrait ? (
                <>
                  {dayMasterLabel}
                  <br />
                  <span className="text-xs text-stone-500 leading-relaxed">{dayMasterTrait}</span>
                </>
              ) : dayMasterLabel,
            ],
            ["Stronger Elements", strongerElements.join(", ") || "-"],
            ...(moderateElements.length ? [["Moderate Elements", moderateElements.join(", ")]] : []),
            ["Weaker Elements", weakerElements.join(", ") || "-"],
            [
              "Useful God",
              `${usefulGod.primaryUsefulGod || "-"} (primary) · ${
                usefulGod.secondaryUsefulGod || "-"
              } (secondary)`,
            ],
          ].map(([label, value]) => (
            <tr key={label} className="border-b border-slate-100 last:border-0 print:border-[#e5d5c0]">
              <td className="bg-slate-50 px-4 py-2.5 font-semibold text-slate-700 print:bg-[#8B1A1A] print:text-white print:w-40">
                {label}
              </td>
              <td className="px-4 py-2.5 text-stone-700 print:bg-[#FAE5D3]">{value}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {natalPillars && (
        <div className="mt-8">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h3 className="text-xl font-bold text-slate-950">Natal Chart</h3>

            {annualPillar?.chinese && (
              <p className="rounded-full bg-amber-50 px-4 py-1.5 text-sm font-semibold text-amber-800">
                {report.annualEnergy?.selectedYear || "Annual"} Pillar:{" "}
                {annualPillar.chinese}
                {annualZodiac?.displayName ? ` (${annualZodiac.displayName})` : ""}
              </p>
            )}
          </div>

          <div className="mt-3 grid grid-cols-2 gap-x-6 gap-y-1 text-xs text-stone-500 md:grid-cols-4">
            <p><span className="font-semibold text-slate-700">Year —</span> ancestral energy, family background and relationship with society. Governs early life (0–16).</p>
            <p><span className="font-semibold text-slate-700">Month —</span> career, parents and productive adult years (17–40). Primary pillar for professional life.</p>
            <p><span className="font-semibold text-slate-700">Day —</span> the self. The Day Heavenly Stem is the Day Master — the chart's core identity. The Day Branch represents the inner self and partner energy.</p>
            <p><span className="font-semibold text-slate-700">Hour —</span> aspirations, children and the later years of life (40+). Reflects what the person is building toward.</p>
          </div>

          <div className="mt-4 overflow-hidden rounded-2xl border border-slate-200">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-slate-50 text-left text-xs font-bold uppercase tracking-[0.12em] text-slate-600">
                  <th className="px-4 py-2.5"></th>
                  {["hour", "day", "month", "year"].map((key) => (
                    <th key={key} className="px-4 py-2.5 capitalize">
                      {key}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                <tr className="border-t border-slate-100">
                  <td className="px-4 py-2.5 font-semibold text-slate-700">
                    Heavenly Stem
                  </td>
                  {["hour", "day", "month", "year"].map((key) => {
                    const pillar = natalPillars[key];
                    return (
                      <td key={key} className="px-4 py-2.5">
                        {pillar?.stem ? (
                          <>
                            <span className="text-lg font-bold text-slate-950">
                              {pillar.stem.zh}
                            </span>{" "}
                            <span className="text-stone-500">
                              {pillar.stem.name} {pillar.stem.element}
                            </span>
                          </>
                        ) : (
                          <span className="text-stone-400">—</span>
                        )}
                      </td>
                    );
                  })}
                </tr>

                <tr className="border-t border-slate-100">
                  <td className="px-4 py-2.5 font-semibold text-slate-700">
                    Earthly Branch
                  </td>
                  {["hour", "day", "month", "year"].map((key) => {
                    const pillar = natalPillars[key];
                    return (
                      <td key={key} className="px-4 py-2.5">
                        {pillar?.branch ? (
                          <>
                            <span className="text-lg font-bold text-slate-950">
                              {pillar.branch.zh}
                            </span>{" "}
                            <span className="text-stone-500">
                              {pillar.branch.animal} {pillar.branch.element}
                            </span>
                          </>
                        ) : (
                          <span className="text-stone-400">—</span>
                        )}
                      </td>
                    );
                  })}
                </tr>

                <tr className="border-t border-slate-100 align-top">
                  <td className="px-4 py-2.5 font-semibold text-slate-700">
                    Hidden Stems
                  </td>
                  {["hour", "day", "month", "year"].map((key) => {
                    const pillar = natalPillars[key];
                    const hiddenTenGods = tenGodByPillar?.[key]?.hiddenStems || [];
                    return (
                      <td key={key} className="px-4 py-2.5">
                        {pillar?.branch?.hiddenStems?.length ? (
                          <div className="space-y-1">
                            {pillar.branch.hiddenStems.map((hidden, i) => (
                              <p key={hidden.key}>
                                <span className="font-semibold text-slate-800">
                                  {hidden.zh}
                                </span>{" "}
                                <span className="text-xs text-stone-500">
                                  {hiddenTenGods[i]?.tenGod || ""}
                                </span>
                              </p>
                            ))}
                          </div>
                        ) : (
                          <span className="text-stone-400">—</span>
                        )}
                      </td>
                    );
                  })}
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      )}

      {!!elementalBalance.length && (
        <div className="mt-8">
          <h3 className="text-xl font-bold text-slate-950">5 Elements Balance</h3>
          <p className="mt-2 text-sm text-stone-500">
            Natal Chart vs. {report.annualEnergy?.selectedYear || "this year"}'s Annual
            Energy, and what each element represents in this chart.
          </p>
          <div className="mt-4 space-y-3">
            {elementalBalance.map((item) => (
              <div
                key={item.name}
                className="rounded-xl border border-slate-200 p-4"
              >
                <p className="text-base font-bold text-slate-950">
                  {item.name} — Natal {Math.round(item.natalPercentage)}% · Annual{" "}
                  {Math.round(item.annualPercentage)}%
                </p>
                {item.roleDescription && (
                  <p className="mt-1 text-sm text-stone-600">
                    {item.name} governs {item.roleDescription}.
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {!!rankedProfiles.length && (
        <div className="mt-8">
          <h3 className="text-xl font-bold text-slate-950">Personality Profile Breakdown</h3>
          <p className="mt-3 text-sm text-stone-500">
            Your personality is shaped by ten archetypal energy patterns derived from your natal chart. Each pattern influences how you think, make decisions, respond under pressure and connect with others. The percentage shows how strongly each pattern is wired into your natural behaviour — a higher score means that energy is dominant and shows up consistently, while a lower score indicates a dormant pattern that may emerge in specific situations or can be consciously developed over time.
          </p>
          <div className="mt-4 space-y-3">
            {rankedProfiles.map((item) => {
              const display = getProfileDisplay(item.profile);
              return (
                <div
                  key={item.profile}
                  className="rounded-xl border border-slate-200 p-4"
                >
                  <p className="text-base font-bold text-slate-950">
                    {display.icon} {Math.round(item.percentage)}% {item.profile}
                    {display.name ? ` — ${display.name}` : ""}
                  </p>
                  {display.subtitle && (
                    <p className="mt-0.5 text-xs font-semibold uppercase tracking-[0.18em] text-amber-700">
                      {display.subtitle}
                    </p>
                  )}
                  {display.theme && (
                    <p className="mt-1.5 text-sm text-stone-600">{display.theme}</p>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </>
  );
}
