export function exportAdminReportToPdf() {
  const style = document.createElement("style");
  style.id = "huangs-print-style";
  style.textContent = `
    @media print {
      @page {
        margin: 1.5cm;
        size: A4;
        /* Blank out browser-injected URL/date/page-number headers and footers */
        @top-left { content: ""; }
        @top-center { content: ""; }
        @top-right { content: ""; }
        @bottom-left { content: ""; }
        @bottom-center { content: "Bazi Analysis generated by huangsjadeiteandjewelry.com."; font-size: 9pt; color: #888; }
        @bottom-right { content: ""; }
      }
      body * { visibility: hidden !important; }
      #admin-full-report, #admin-full-report * { visibility: visible !important; }
      #admin-full-report { position: absolute !important; left: 0 !important; top: 0 !important; width: 100% !important; border: none !important; box-shadow: none !important; border-radius: 0 !important; padding: 0 !important; }
      .print-no-export { display: none !important; }
      .print-footer { display: none !important; }
      .print-cover {
        display: flex !important;
        flex-direction: column !important;
        align-items: center !important;
        justify-content: center !important;
        text-align: center !important;
        min-height: 85vh;
        padding: 5cm 2cm 3cm 2cm !important;
        page-break-after: always;
      }
      .print-cover img {
        display: block !important;
        margin: 0 auto 1.5rem auto !important;
        max-width: 200px !important;
        width: auto !important;
        height: auto !important;
      }
      .print-cover > h1,
      .print-cover > p {
        text-align: center !important;
        width: 100% !important;
      }
      .print-cover-body {
        text-align: left !important;
        max-width: 480px !important;
        margin: 1rem auto 0 auto !important;
      }
      table { border-collapse: collapse; width: 100%; }
      .print-break-before { page-break-before: always; }
    }
  `;
  document.head.appendChild(style);
  window.print();
  setTimeout(() => {
    const existing = document.getElementById("huangs-print-style");
    if (existing) existing.remove();
  }, 1500);
}
